// Generated by scripts/sync-release-notes.mjs. Do not edit manually.
import type { ReleaseNotesContent } from "./types"

export const currentReleaseNotes = {
  version: "1.2.6",
  date: "2026-08-28",
  notes: {
    en: '### 🚀 New Features\n\n- **Perplexity support** — The online adapter library now includes Perplexity (www.perplexity.ai); installing the pack enables outlines with user queries, basic export, chat width, Zen Mode, new chat, prompt insertion, and theme sync on conversation pages.\n- **Baidu Wenxin support** — The online adapter library now includes Baidu Wenxin (wenxin.baidu.com); installing the pack enables outlines with user queries, basic export, chat width, Zen Mode, new chat, and prompt insertion on conversations page.\n\n### 🐛 Bug Fixes\n\n- **Claude Incognito chat adaptation** — Fixed conversation export and copy failing with "Conversation not found" in Claude Incognito chats (claude.ai/new?incognito=); the export file is titled from the first user message, and smart panel avoidance now works on Incognito pages. (#879)',
    zh: "### 🚀 新增功能\n\n- **Perplexity 支持** — 在线适配库新增 Perplexity（www.perplexity.ai），安装适配包后即可在对话页使用大纲（含用户提问）、基础导出、对话宽度、禅模式、新对话、提示词插入和主题切换功能。\n- **百度文心支持** — 在线适配库新增百度文心（wenxin.baidu.com），安装适配包后即可在对话页使用大纲（含用户提问）、基础导出、对话宽度、禅模式、新对话和提示词插入功能。\n\n### 🐛 问题修复\n\n- **适配 Claude 隐身对话** — 修复 Claude 隐身对话（claude.ai/new?incognito=）中导出和复制对话提示“Conversation not found”失败的问题，导出文件以首条提问作为标题，智能避让在隐身对话页恢复生效。(#879)",
  },
  fullChangelogUrls: {
    en: "https://ophel.app/docs/changelog",
    zh: "https://ophel.app/docs/zh/changelog",
  },
  media: [],
} as const satisfies ReleaseNotesContent
