// Generated by scripts/sync-release-notes.mjs. Do not edit manually.
import type { ReleaseNotesContent } from "./types"

export const currentReleaseNotes = {
  version: "1.2.11",
  date: "2026-09-30",
  notes: {
    en: "**⚠️ Notice — Our GitHub account has been temporarily suspended in error, and we are actively appealing. Until it is restored, GitHub links (repository, issue tracker) and the online adapter library in the Adapter Center may be unavailable. If you run into any problems, please let us know on [Discord](https://discord.gg/rmPzb6Cx9u).**\n\n**📢 Notice — ChatGPT is currently rolling out a major web redesign to select accounts, significantly restructuring the sidebar history, composer, and chat layout, which causes the extension's existing selectors to stop functioning. As none of our developer accounts have received this rollout yet, dynamic interactions cannot be tested and full adaptation is temporarily blocked until our accounts receive the update, ChatGPT rolls it out globally, or a community member can grant temporary account access for debugging. If you have a test account on the new interface and are willing to assist, please reach out to us on [Discord](https://discord.gg/rmPzb6Cx9u).**\n\n### ✨ Improvements\n\n- **Chats tab improvements** — Improved filters, search, batch actions, and drag-and-drop reordering in conversation management. (#965)\n- **Outline tab improvements** — The level slider now supports drag adjustment, the toolbar automatically compacts on narrow panels, row alignment is improved, and the export button shimmer stops after the first click. (#966)\n- **Prompts tab improvements** — Improved category filtering, variable tags, and empty-state guidance for prompts. (#967)\n\n### 🐛 Bug Fixes\n\n- **Attachment-only questions missing from outline and export** — Fixed an issue where questions containing only images or files were missing from the outline on DeepSeek and Claude, or omitted from AI Studio exports; the outline now shows the attachment file name and exports include the attachments. (#970)",
    zh: "> 🇨🇳 **国庆快乐！祝各位节日愉快，阖家安康！**\n\n**⚠️ 公告 — 我们的 GitHub 账号暂时被误封禁，目前正在积极申诉。恢复之前，GitHub 仓库、问题反馈页面以及适配中心的在线适配库可能暂时无法访问。如遇到任何问题，请前往 [Discord](https://discord.gg/rmPzb6Cx9u) 反馈。**\n\n**📢 公告 — ChatGPT 近期正在分批灰度全新网页架构，侧边栏历史记录、输入框及聊天窗口的底层结构发生重大调整，导致插件现有识别规则全面失效。由于开发者手头的所有账号均未命中灰度，缺乏动态交互排查环境，目前暂时无法开展适配。需等待开发者账号被灰度到、官方全量推送新版，或有命中灰度的用户协助借号调试后才能恢复支持。如您手头有已灰度的账号并愿意协助调试，欢迎前往 [Discord](https://discord.gg/rmPzb6Cx9u) 联系我们。**\n\n### ✨ 功能优化\n\n- **对话管理体验优化** — 优化对话筛选、搜索、批量操作与拖拽排序体验，对话管理更清晰顺畅。 (#965)\n- **大纲标签页优化** — 层级滑块支持按住拖动调整，窄面板下工具栏自动精简，优化行对齐细节，导出按钮的流光提示点击后不再重复出现。 (#966)\n- **提示词标签页优化** — 优化提示词分类筛选、变量标识与空列表引导提示，管理和查找提示词更便捷。 (#967)\n\n### 🐛 问题修复\n\n- **纯文件提问大纲与导出缺失** — 修复仅发送图片或文件而未输入文字的提问在 DeepSeek、Claude 大纲中缺失，以及 AI Studio 导出时整条丢失的问题；现在大纲正常以附件文件名展示此类提问，附件也会随提问一并导出。 (#970)",
  },
  fullChangelogUrls: {
    en: "https://ophel.app/docs/changelog",
    zh: "https://ophel.app/docs/zh/changelog",
  },
  media: [],
} as const satisfies ReleaseNotesContent
